version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-and-deploy:
    executor:
      name: node/default
    docker:
      - image: circleci/node:10.0-browsers # < an arbitrarily chosen docker image.
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run:
                name: Trigger docker remotely
                command: $DOCKER_HUB_TRIGGER # < EnvVar set in CircleCI
workflows:
    build-and-test-and-deploy:
      jobs:
        - build-and-test-and-deploy
